ekf_filter_node:
  frequency: 50  # Filter update rate (adjust based on your system)
  sensor_timeout: 0.1
  two_d_mode: false  # Set to true if your robot only moves in 2D

  # IMU data topic
  imu0: imu/data
  imu0_config: [false, false, false,  # x, y, z position (we don't get position from IMU)
                false, false, false,  # x, y, z velocity (we don't get velocity from IMU)
                true,  true,  true,   # Roll, pitch, yaw (orientation)
                false,  false,  false,   # Angular velocity x, y, z
                true,  true,  true]   # Linear acceleration x, y, z

  imu0_differential: false
  imu0_remove_gravitational_acceleration: false
